### ISSUE TITLE
Query 

### ISSUE THREAD

**Issue by HarishBaskaran-CA** [KarlHeitmann/rails_routes_parser#1]
Can you explain what this codebase does ? 

is this code, able to static parse a rails's routes.rb file and print the insights out of it ?

**Comment by KarlHeitmann** [comment]
Yeah, it's meant to static parse the rails routes. First run:

> $ rails routes > routes.txt

Then you can run the current project, it will read the file and parse its insights.

The purpose of this module, is to be used inside [rg_explorer](https://github.com/KarlHeitmann/rg_explorer), rg_explorer is a wrapper for [RipGrep](https://github.com/BurntSushi/ripgrep), it lets the user explore a codebase by running rip grep and present the data in a nice TUI.

When you are exploring a rails project, sometimes you will end up in files inside the `app/views/` folder. It would be nice that if rg_explorer finds a match inside `app/views/` folder, it will parse rails routes and show you which URL you have to type in the browser to access the file you are viewing.

**Comment by HarishBaskaran-CA** [comment]
i have exported a routes.rb file from a project. 

can you help me with the code - 
how to trigger your parser on the exported routes file. 

I just need the list of urls and it's related controller#actions from routes.rb. 
It will save my time a lot, kindly let me know.

**Comment by KarlHeitmann** [comment]
Sorry the delay @HarishBaskaran-CA , I just went on vacation these 2 weeks. This project is still WIP. The main problem is [here](https://github.com/KarlHeitmann/rails_routes_parser/blob/68077fdb56c3322c18ee5061ee61999c880c3b9e/src/main.rs#L33), you'll have to add more cases to the match condition. Take a look at this example:

```
                    space GET  (/:database)/space(.:format)                     pg_hero/home#space
           relation_space GET  (/:database)/space/:relation(.:format)           pg_hero/home#relation_space
              index_bloat GET  (/:database)/index_bloat(.:format)               pg_hero/home#index_bloat
             live_queries GET  (/:database)/live_queries(.:format)              pg_hero/home#live_queries
                  queries GET  (/:database)/queries(.:format)                   pg_hero/home#queries
               show_query GET  (/:database)/queries/:query_hash(.:format)       pg_hero/home#show_query
                   system GET  (/:database)/system(.:format)                    pg_hero/home#system
                cpu_usage GET  (/:database)/cpu_usage(.:format)                 pg_hero/home#cpu_usage
         connection_stats GET  (/:database)/connection_stats(.:format)          pg_hero/home#connection_stats
    replication_lag_stats GET  (/:database)/replication_lag_stats(.:format)     pg_hero/home#replication_lag_stats
               load_stats GET  (/:database)/load_stats(.:format)                pg_hero/home#load_stats
         free_space_stats GET  (/:database)/free_space_stats(.:format)          pg_hero/home#free_space_stats
                  explain GET  (/:database)/explain(.:format)                   pg_hero/home#explain
                     tune GET  (/:database)/tune(.:format)                      pg_hero/home#tune
              connections GET  (/:database)/connections(.:format)               pg_hero/home#connections
              maintenance GET  (/:database)/maintenance(.:format)               pg_hero/home#maintenance
                     kill POST (/:database)/kill(.:format)                      pg_hero/home#kill
kill_long_running_queries POST (/:database)/kill_long_running_queries(.:format) pg_hero/home#kill_long_running_queries
                 kill_all POST (/:database)/kill_all(.:format)                  pg_hero/home#kill_all
       enable_query_stats POST (/:database)/enable_query_stats(.:format)        pg_hero/home#enable_query_stats
                          POST (/:database)/explain(.:format)                   pg_hero/home#explain
        reset_query_stats POST (/:database)/reset_query_stats(.:format)         pg_hero/home#reset_query_stats
             system_stats GET  (/:database)/system_stats(.:format)              redirect(301, system)
              query_stats GET  (/:database)/query_stats(.:format)               redirect(301, queries)
                     root GET  /(:database)(.:format)                           pg_hero/home#index

```

If you split each line of the above routes.txt file by space, take a look at the second to last line: `query_stats GET  (/:database)/query_stats(.:format)               redirect(301, queries)`, the `controller_action` attribute of `RouteNode` will have value of `redirect(301` instead of the correct value: `redirect(301, queries)`. Also, there are some cases where the PREFIX is not present, you should handle that case.

The actual code I put `3` and `4` as possible matches for [ss.clone().count()](https://github.com/KarlHeitmann/rails_routes_parser/blob/68077fdb56c3322c18ee5061ee61999c880c3b9e/src/main.rs#L18), but it is a mistake, it should be `5` and `4`.... this is still WIP.

**Comment by KarlHeitmann** [comment]
Hey @HarishBaskaran-CA , I moved this code to a new repo called [rails_explorer](https://github.com/KarlHeitmann/rails_explorer). It is part of my series of Rust explorers with TUI. rails_explorer is parsing the rails routes (its first feature) and displays it in a nice TUI. Check out that repo and let me know if it works for you.

Once you cloned the project, you only need to do this command `rails routes > routes.txt` on you rails application and copy the file `routes.txt` to the root folder of your local `rails_explorer` clone. Then run `cargo run` and it --should-- work.

The project only needs a way to switch between "command mode" and "edit mode". Be careful if you type the `q` letter because that will quit the program even though you might be filtering the routes of your `routes.txt` file.
